# Generated by Django 4.2.30 on 2026-06-03 18:10

from django.db import migrations, models


def normalize_order_statuses(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Order.objects.filter(status__in=['paid', 'processing']).update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem_category_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='uploaded_image',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
        migrations.RunPython(normalize_order_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
