# Generated by Django 4.2.30 on 2026-06-03 18:45

from django.db import migrations, models


def migrate_payment_state(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Payment = apps.get_model('shop', 'Payment')

    for payment in Payment.objects.select_related('order').all():
        old_method = payment.method
        if old_method in {'bkash', 'nagad'}:
            payment.method = 'sslcommerz'
            payment.gateway_name = old_method
        elif old_method == 'cash_on_delivery':
            payment.gateway_name = 'cash_on_delivery'
        else:
            payment.gateway_name = old_method or 'cash_on_delivery'

        if payment.status == 'refunded':
            payment.status = 'cancelled'
        if payment.status == 'pending' and payment.method == 'cash_on_delivery':
            payment.status = 'unpaid'
        if payment.status == 'paid':
            payment.payment_date = payment.paid_at

        payment.save(update_fields=['method', 'gateway_name', 'status', 'payment_date'])

    for order in Order.objects.prefetch_related('payments').all():
        payment = order.payments.order_by('-created_at').first()
        if payment:
            order.payment_method = payment.method
            order.payment_status = payment.status
        else:
            order.payment_method = 'cash_on_delivery'
            order.payment_status = 'unpaid'
        order.save(update_fields=['payment_method', 'payment_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage_uploaded_image_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('sslcommerz', 'Online payment - SSLCOMMERZ')], default='cash_on_delivery', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_payment_state, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('sslcommerz', 'SSLCOMMERZ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
